### ISSUE TITLE
Generar Documento Requerimiento

### ISSUE THREAD

**Issue by StuardMS** [StuardMS/P-PV-BUSES#2]

**Comment by keysiquiros** [comment]
Introducción
El objetivo del sistema a realizar se va a enfocar en una App para el control de becas de transporte de una institución para llevar un mejor orden y manejo de datos. En este proyecto se busca implementar un sistema que puede ser utilizado en instituciones educativas públicas y privadas, que permita un manejo de las becas de transporte activas, creación de carnets, scanneo de carnets, consultas de información básica, consultas sobre el uso del beneficio de la beca por día, de los estudiantes, utilizando el ambiente de desarrollo Android Studio.

Propósito
El propósito de este documento busca especificar formalmente todos los requerimientos necesarios para el desarrollo del sistema. Busca ser una herramienta que deberá ser usada por las personas encargadas de diseñar  y desarrollar el sistema y de esta forma verificar que el software cumple con los requerimientos del cliente.


Alcance del proyecto
Este proyecto beneficiará en el control del ingreso de los estudiantes al autobús de las instituciones que lo implementen, busca facilitar la gestión del registro, control y uso por medio de una aplicación para dispositivos móviles. 

Características de los usuarios
Los usuarios que utilizaran el sistema se dividen en dos grupos, que son los que llevaran a cargo funciones de administrador como registro de estudiantes y creación del carnet y modificación de información, además de las funciones básicas como scanneo, y visualización y control de la información, por otro lado, estarán los usuarios que únicamente pueden llevar a acabo funciones de scanneo de carnets, visualización de información del estudiante y control de quienes hicieron uso de la beca.


Requerimientos del sistema
-El sistema debe contar con un inicio de sesión que valide los datos del usuario que va a ingresar y un limitador de niveles.
-Verificar cuando el estudiante tiene una beca activa, la cual se verificará mediante un lector de código el status de dicha beca.
-Debe permitir realizar consultas como el listado de estudiantes y el tipo de beca que tiene.
-Debe permitir realizar consultas por día, de quienes utilizaron el beneficio de la beca.
-Debe dar acceso a verificar quienes no utilizaron el beneficio de la beca.
-Ingresar manualmente el número de carnet, en caso de fallos en el lector de códigos.
-Creación del carnet e información del estudiante.
-Creación interfaz grafica que cuente con login, consulta de usuarios, consulta de estudiantes, creación del carnet, lector del carnet, consulta de utilización o no utilización del beneficio.
-Creación de base de datos que contenga la información de los usuarios y estudiantes.

Restricciones
-Este sistema solo puede ser utilizado en dispositivos con sistema operativo Android.
-Habrá limitaciones de acceso de funcionalidades, dependiendo del tipo de usuario.
-Un estudiante no puede hacer uso del beneficio de la beca mas de una vez por día.
