### ISSUE TITLE
Crear compilado y código del proyecto 

### ISSUE THREAD

**Issue by StuardMS** [StuardMS/P-PV-BUSES#4]
Se deberá crear mediante la herramienta de Android Studio el compilado del sistema, deberá ir dentro de la carpeta "Code" del repositorio.
Además se deberá corroborar por parte de cada miembro del equipo que se ejecute de una forma correcta.

**Comment by JPabloCR** [comment]
Compilado ya creado.
Emulador a utilizar seria el Nexus 6.
